<?php

namespace Mbp\TestBundle\Entity;
use Gedmo\Tree\Entity\Repository\ClosureTreeRepository;

/**
 * FormulasCRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormulasCRepository extends \Gedmo\Tree\Entity\Repository\ClosureTreeRepository
{
	public function queryFormulaCompleta($nodo)
	{
		$em = $this->getEntityManager();
    	$repo=$em->getRepository('MbpTestBundle:FormulasC');
    	
    	$dql = "SELECT node.id, art.codigo, node.letra
    			FROM Mbp\TestBundle\Entity\FormulasClosure c
    			INNER JOIN c.descendant node 
    			INNER JOIN node.idArt art
    			WHERE c.ancestor = :node AND c.descendant <> :node";

    	$qb = $em->createQuery($dql);
    	$qb->setParameter('node',$nodo);

    	return $qb->getArrayResult();

	}
}
