<?php

namespace Mbp\ComprasBundle\Entity;

/**
 * OrdenCompraDetalleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdenCompraDetalleRepository extends \Doctrine\ORM\EntityRepository
{
}
