<?php

namespace Mbp\ComprasBundle\Entity;

/**
 * PedidoInternoDetalleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PedidoInternoDetalleRepository extends \Doctrine\ORM\EntityRepository
{
}
