<?php

namespace Mbp\ComprasBundle\Entity;

/**
 * PedidosInternosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PedidosInternosRepository extends \Doctrine\ORM\EntityRepository
{
}
