<?php

namespace Mbp\UtilitariosBundle\Entity;

/**
 * ViajeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ViajeRepository extends \Doctrine\ORM\EntityRepository
{
}
