<?php

namespace Mbp\PersonalBundle\Entity;

/**
 * CategoriasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriasRepository extends \Doctrine\ORM\EntityRepository
{
	/*
	 * return json msg
	 */
	public function listCategorias()
	{
		$em = $this->getEntityManager();
		
		try{
			$dql = 'SELECT cat, sin FROM MbpPersonalBundle:Categorias cat JOIN cat.idSindicato sin
					WHERE cat.inactivo = 0';
			$query = $em->createQuery($dql);
			$res = $query->getArrayResult();
			
			$rec = array();
			$i=0;
			foreach($res as $reg){
				$rec[$i] = $reg;
				$rec[$i]['sindicato'] = $reg['idSindicato']['sindicato'];
				$rec[$i]['idCategoria'] = $reg['id'];
				$rec[$i]['idSindicato'] = $reg['idSindicato']['id'];
				unset($rec[$i]['id']);
				$i++;
			}
			
			
			$jsonRes = json_encode(array(
				'items' => $rec
			));
			
			echo $jsonRes;	
		}catch(\Doctrine\ORM\ORMException $e){
			$this->get('logger')->error($e->getMessage());
		}
		
	}
	
	/*
	 * @param	| jsonData
	 * return	| json msg
	 */
	public function crearCategoria($jsonData)
	{
		$em = $this->getEntityManager();
		
		
		try{
			$obj = 0;
			if($jsonData->idCategoria > 0){
				$repoCategorias = $em->getRepository('MbpPersonalBundle:Categorias');
				$obj = $repoCategorias->find($jsonData->idCategoria);
			}else{
				$obj = new Categorias();	
			}
			
			$repoSindicato = $em->getRepository('MbpPersonalBundle:Sindicatos');
			$sindicato = $repoSindicato->find($jsonData->idSindicato);
						
			$obj->setidSindicato($sindicato);
			$obj->setcategoria($jsonData->categoria);			
			$obj->setsalario($jsonData->salario);
			$em->persist($obj);
			$em->flush();
			
			echo json_encode(array(
				'success' => true,
				'items' => array(
					'idCategoria' => $obj->getId(),
					'idSindicato' => $jsonData->idSindicato,
					'sindicato' => $sindicato->getSindicato(),
					'salario' => $jsonData->salario,
					'categoria' => $jsonData->categoria
				)
			));
		}catch(\Doctrine\ORM\ORMException $e){
			$this->get('logger')->error($e->getMessage());
		}		
	}
	
	/*
	 * @param	| jsonData
	 * return	| json msg
	 */
	public function borrarCategoria($jsonData)
	{
		$em = $this->getEntityManager();
		$repo = $em->getRepository('MbpPersonalBundle:Categorias');
		
		try{
			$obj = $repo->find($jsonData->idCategoria);
			$obj->setInactivo(true);
			$em->persist($obj);
			
			$em->flush();
			
			echo json_encode(array(
				'success' => true
			));			
		}catch(\Doctrine\ORM\ORMException $e){
			$this->get('logger')->error($e->getMessage());
		}		
	}
}






















