<?php

namespace Mbp\PersonalBundle\Entity;

/**
 * CuentaEmpleadosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CuentaEmpleadosRepository extends \Doctrine\ORM\EntityRepository
{
}
