<?php

namespace Mbp\PersonalBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DepartamentosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepartamentosRepository extends \Doctrine\ORM\EntityRepository
{
	/*
	 * return	json departamentos
	 */
	public function listarDepartamentos()
	{
		$em = $this->getEntityManager();
		
		$dql = 'SELECT dep, prov FROM MbpPersonalBundle:Departamentos dep JOIN dep.provinciaId
				ORDER BY dep.nombre ASC';
		$query = $em->createQuery($dql);
		$res = $query->getArrayResult();
		
		$jsonRes = json_encode(array(
			'items' => $res
		));
		
		echo $jsonRes;
	}
}
