<?php

namespace Mbp\PersonalBundle\Entity;

/**
 * PeriodosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PeriodosRepository extends \Doctrine\ORM\EntityRepository
{
}
