<?php

namespace Mbp\PersonalBundle\Entity;

/**
 * PersonalConceptosSueldoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonalConceptosSueldoRepository extends \Doctrine\ORM\EntityRepository
{
	public function creaDatoFijoPersona($idP, $idDatoFijo)
	{
		$em = $this->getEntityManager();
		$repoConcepto = $em->getRepository('MbpPersonalBundle:CodigoSueldos');
		$repoPersona = $em->getRepository('MbpPersonalBundle:Personal');
		
		try{
			
			$obj = new PersonalConceptosSueldo();
			$objPersona = $repoPersona->find($idP);
			$objDatoFijo = $repoConcepto->find($idDatoFijo);
			
			$obj->setPersonalId($objPersona);
			$obj->setCodigoId($objDatoFijo);
			
			$em->persist($obj);
			$em->flush();	
			
			echo json_encode(array(
				'success' => true,
				'items' => array(
					'datosFijos' => array(
						'codigo' => $objDatoFijo->getId(),
						'descripcion' => $objDatoFijo->getDescripcion(),
						'importe' => $objDatoFijo->getImporte(),
					)					
				) 
			));
						
		}catch(\Doctrine\ORM\ORMException $e){
			
		}
	}
	
	/*
	 * ELIMINAR DATO FIJO ASOCIADO A UNA PERSONA
	 * @param $idP	| int
	 * @param $idConcepto	| int
	 */
	public function eliminarConcepto($idP, $idConcepto)
	{
		$em = $this->getEntityManager();
		$repoPersonalConcepto = $em->getRepository('MbpPersonalBundle:PersonalConceptosSueldo');
		
		try{
			$query = $repoPersonalConcepto->createQueryBuilder('p')
			->select('p')
			->where('p.personal_id = :idP')
			->andWhere('p.codigo_id = :idConcepto')
			->setParameter('idP', $idP)
			->setParameter('idConcepto', $idConcepto)
			->getQuery();
			
			$res = $query->getResult();
			
			if(empty($res)){
				throw new \Exception("No se encontró el registro", 1);
				
			}
			
			$em->remove($res[0]);
			$em->flush();
			
			echo json_encode(array(
				'success' => true
			));
		}catch(\Doctrine\ORM\ORMException $e){
			$this->get('logger')->error($e->getMessage());
		}
	}
}





