<?php

namespace Mbp\PersonalBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProvinciasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProvinciasRepository extends \Doctrine\ORM\EntityRepository
{
	/*
	 * return	json provincias
	 */
	public function listarProvincias()
	{
		$em = $this->getEntityManager();
		
		$dql = 'SELECT prov.id as idProvincia, prov.nombre FROM MbpPersonalBundle:Provincias prov';
		$query = $em->createQuery($dql);
		$res = $query->getArrayResult();
		
		$jsonRes = json_encode(array(
			'items' => $res
		));
		
		echo $jsonRes;
	}
}
