<?php

namespace Mbp\PersonalBundle\Entity;

/**
 * RecibosDetalleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecibosDetalleRepository extends \Doctrine\ORM\EntityRepository
{
}
