<?php

namespace Mbp\PersonalBundle\Entity;

/**
 * RecibosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecibosRepository extends \Doctrine\ORM\EntityRepository
{
}
