mbp_calidad_trazabilidad:
    resource: "@MbpCalidadBundle/Controller/TrazabilidadController.php"
    type:     annotation
    prefix:   /trazabilidad

mbp_calidad_trazabilidad:
    resource: "@MbpCalidadBundle/Controller/ReportesController.php"
    type:     annotation
    prefix:   /reportes

mbp_calidad_ingresos:
    resource: "@MbpCalidadBundle/Controller/ControlRecepcionController.php"
    type:     annotation
    prefix:   /recepcion

mbp_calidad_correlativos:
    path:     /correlativos
    defaults: { _controller: MbpCalidadBundle:Default:correlativos }
    options:
       expose: true

mbp_calidad_newcorrelativo:
    path:     /newcorrelativo
    defaults: { _controller: MbpCalidadBundle:Default:newcorrelativo }
    options:
       expose: true

mbp_calidad_updatecorrelativo:
    path:     /updatecorrelativo
    defaults: { _controller: MbpCalidadBundle:Default:updatecorrelativo }
    options:
       expose: true

mbp_calidad_destroycorrelativo:
    path:     /destroycorrelativo
    defaults: { _controller: MbpCalidadBundle:Default:destroycorrelativo }
    options:
       expose: true

#URL Control de estanqueidad

mbp_calidad_addEstanqueidadReg:
    path:     /addEstanqueidadReg
    defaults: { _controller: MbpCalidadBundle:Default:addEstanqueidadReg }
    options:
       expose: true


mbp_calidad_listEstanqueidad:
    path:     /listEstanqueidad
    defaults: { _controller: MbpCalidadBundle:Default:listEstanqueidad }
    options:
       expose: true

mbp_calidad_deleteEstanqueidad:
    path:     /deleteEstanqueidad
    defaults: { _controller: MbpCalidadBundle:Default:deleteEstanqueidadReg }
    options:
       expose: true