parameters:
#    mbp_calidad.example.class: Mbp\CalidadBundle\Example

services:
#    mbp_calidad.example:
#        class: %mbp_calidad.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
