imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache: apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    channels: [facturacion, comandos]
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type:  console
        facturacion:
            type:    stream
            path:    "%kernel.logs_dir%/facturacion.log"
            level:   error
            channels: [facturacion]
        comandos:
            type:    stream
            path:    "%kernel.logs_dir%/comandos.log"
            level:   error
            channels: [comandos]

services:
    mbp.faele:
        class: Mbp\FinanzasBundle\Clases\Faele
        arguments: [%ptoVta_prod%, %docTipo%, %cert_prod%, %privateKey_prod%, %url_prod%, %wsfeUrl_prod%, %cuit_prod%]