
# app/config/security.yml
security:
    access_denied_url: /foo/error403
    firewalls:   
        secured_area2:
            pattern: ^/api/*
            stateless: true
            simple_preauth:
                authenticator: apikey_authenticator
            provider: api_key_user_provider

        secured_area:          
            access_denied_handler: app.security.access_denied_handler
            pattern:    ^/
            anonymous: ~

            form_login:
                login_path:  login
                check_path:  login_check
                default_target_path: /index  
            logout:
                path:   /logout
                target: login                    
            remember_me:
                key: prueba123
                lifetime: 604800 # 7 * 24 * 3600 = 604.800 = 1 semana
        
        
            

    access_control:
        - { path: ^/index, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/apiLogin, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/web/*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/articulos/extranet/*, roles: ROLE_EXTRANET }
        - { path: ^/articulos/*, roles: ROLE_FABRICA }        
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/calidad/trazabilidad, roles: ROLE_FABRICA }
        - { path: ^/calidad, roles: ROLE_CALIDAD }
        - { path: ^/personal, roles: ROLE_CALIDAD }
        - { path: ^/sueldos, roles: ROLE_ADMINISTRACION }
        - { path: ^/adm, roles: ROLE_ADMINISTRACION }
        - { path: ^/clientes/clientesearch/*, roles: ROLE_FABRICA }
        - { path: ^/clientes/*, roles: ROLE_CLIENTE }        
        #- { path: ^/, roles: ROLE_USER }
        
    role_hierarchy:
        ROLE_ADMIN: ROLE_CALIDAD, ROLE_ADMINISTRACION        
        ROLE_ADMINISTRACION: ROLE_CALIDAD
        ROLE_CALIDAD: ROLE_USER, ROLE_EXTRANET, ROLE_CLIENTE, ROLE_FABRICA
        ROLE_FABRICA: ROLE_EXTRANET
        #ROLE_CLIENTE: ROLE_USER
      
    providers: 
        chain_provider:
            chain:
                providers: [administrators, api_key_user_provider]
        administrators:
            entity: { class: MbpSecurityBundle:Users, property: username }
        api_key_user_provider:
            id: api_key_user_provider


    encoders:
        Mbp\SecurityBundle\Entity\Users:
            algorithm:        bcrypt
            cost:             12
        Symfony\Component\Security\Core\User\User:
            algorithm:        bcrypt
            cost:             12


    acl:
        connection: default
    
        