
# app/config/security.yml
security:
    access_denied_url: /foo/error403
    firewalls:        
        secured_area:
            access_denied_handler: app.security.access_denied_handler
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path:  login
                check_path:  login_check
                default_target_path: /index  
            logout:
                path:   /logout
                target: login                    
            remember_me:
                key: prueba123
            

    access_control:
        - { path: ^/index, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/web/*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/articulos/extranet/*, roles: ROLE_EXTRANET }
        - { path: ^/articulos/*, roles: ROLE_ADMINISTRACION }        
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/calidad, roles: ROLE_CALIDAD }
        - { path: ^/personal, roles: ROLE_CALIDAD }
        - { path: ^/sueldos, roles: ROLE_ADMINISTRACION }
        - { path: ^/adm, roles: ROLE_ADMINISTRACION }
        - { path: ^/clientes/*, roles: ROLE_CLIENTE }
        #- { path: ^/, roles: ROLE_USER }
        
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER, ROLE_CALIDAD, ROLE_ADMINISTRACION, ROLE_CLIENTE, ROLE_EXTRANET
        ROLE_CALIDAD: ROLE_EXTRANET
        ROLE_ADMINISTRACION: ROLE_USER, ROLE_EXTRANET, ROLE_CALIDAD
        #ROLE_CLIENTE: ROLE_USER
      
    providers: 
        chain_provider:
            chain:
                providers: [administrators, in_memory]
        administrators:
            entity: { class: MbpSecurityBundle:Users, property: username }        
        in_memory:
            memory:
                users:
                    admin: { password: d033e22ae348aeb5660fc2140aec35850c4da997, roles: 'ROLE_ADMIN' }


    encoders:
        Mbp\SecurityBundle\Entity\Users:
            algorithm:        bcrypt
            cost:             12
        Symfony\Component\Security\Core\User\User:
            algorithm:        bcrypt
            cost:             12


    acl:
        connection: default
    
        