<?php

namespace Mbp\FinanzasBundle\Entity;

/**
 * BancosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BancosRepository extends \Doctrine\ORM\EntityRepository
{
}
