<?php

namespace Mbp\FinanzasBundle\Entity;

/**
 * CCClientesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CCClientesRepository extends \Doctrine\ORM\EntityRepository
{	
	public function listarCCClientes($idCliente){
		$em = $this->getEntityManager()->getConnection();
		
		// prepare statement
		$sth = $em->prepare("CALL listarCCCliente($idCliente)");
		
		// execute and fetch
		$sth->execute();
		$res = $sth->fetchAll();
		
		
		return $res;
	
	}
}
