<?php

namespace Mbp\FinanzasBundle\Entity;

/**
 * CCClientesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CCClientesRepository extends \Doctrine\ORM\EntityRepository
{
	public function listarCCClientes($idCliente){
		$em = $this->getEntityManager();
		$repo = $em->getRepository('MbpFinanzasBundle:CCClientes');
		
				
		$res = $repo->createQueryBuilder('cc')
			->select(
				"DATE_FORMAT(cc.fechaEmision, '%d-%m-%Y') as emision,
				CASE WHEN cc.cobranzaId IS NOT NULL THEN CONCAT('COBRANZA N° ', cob.id) ELSE CONCAT(tipo.descripcion, ' N° ', fc.ptoVta, '-', fc.fcNro) END AS concepto, 
				CASE WHEN cc.cobranzaId IS NOT NULL THEN true ELSE false END AS detalle,
				DATE_FORMAT(cc.fechaVencimiento, '%d-%m-%Y') as vencimiento,
				cc.debe,
				cc.haber,
				SUM(cc2.debe) - SUM(cc2.haber) AS saldo,
				fc.id as idF,
				cob.id as idCob
				")
			->leftJoin('cc.facturaId', 'fc')
			->leftJoin('fc.tipoId', 'tipo')
			->leftJoin('cc.cobranzaId', 'cob')//op x cob
			->leftJoin('fc.clienteId', 'clienteFc') //provFc x clienteFc
			->leftJoin('cob.clienteId', 'clienteCob') //provOP x clienteCob
			->leftJoin('Mbp\FinanzasBundle\Entity\CCClientes', 'cc2', \Doctrine\ORM\Query\Expr\Join::WITH, 'cc.id >= cc2.id')
			->where('clienteFc.id = :idCliente')
			->orWhere('clienteCob.id = :idCliente')
			->setParameter('idCliente', $idCliente)	
			->groupBy('cc.id')		
			->getQuery()
			->getArrayResult();
		
		return $res;
	
	}
}
