<?php

namespace Mbp\FinanzasBundle\Entity;

/**
 * CentroCostosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CentroCostosRepository extends \Doctrine\ORM\EntityRepository
{
	/*
	 * Consulta todos los centros de costos y devuleve un array
	 * */
	 public function listarCentroCostos()
	 {
	 	$em = $this->getEntityManager();
		$repo = $em->getRepository('MbpFinanzasBundle:CentroCostos');
		
		$res = $repo->createQueryBuilder('c')
				->select('')
				->getQuery()
				->getArrayResult();
				
		return $res;
	 }
}
