<?php

namespace Mbp\FinanzasBundle\Entity;

/**
 * CobranzasDetalleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CobranzasDetalleRepository extends \Doctrine\ORM\EntityRepository
{
}
