<?php
namespace Mbp\FinanzasBundle\Entity;

/**
 * CobranzasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CobranzasRepository extends \Doctrine\ORM\EntityRepository
{
	public function listaPagosClientes($idCliente)
	{
		$em = $this->getEntityManager();
		$repoCobranzas = $em->getRepository('MbpFinanzasBundle:Cobranzas');
		
		try{
			$qbPagos = $repoCobranzas->createQueryBuilder('cob')
				->select('')
				->join('cob.clienteId', 'cliente')
				->where('cliente.id = :idCliente')
				->setParameter('idCliente', $idCliente)	
				->getQuery();
			$resulPagos = $qbPagos->getResult();
			
			if(empty($resulPagos)){
					return;
				}
			
		}catch(\Doctrine\ORM\ORMException $e){
			$this->get('logger')->error($e->getMessage());
		}
		return $resulPagos;
	}
}
