<?php

namespace Mbp\FinanzasBundle\Entity;

/**
 * ConceptosBancoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConceptosBancoRepository extends \Doctrine\ORM\EntityRepository
{
}
