<?php

namespace Mbp\FinanzasBundle\Entity;

/**
 * CotizacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CotizacionRepository extends \Doctrine\ORM\EntityRepository
{
}
