<?php

namespace Mbp\FinanzasBundle\Entity;

/**
 * CuentasBancariasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CuentasBancariasRepository extends \Doctrine\ORM\EntityRepository
{
}
