<?php

namespace Mbp\FinanzasBundle\Entity;

/**
 * DetalleCotizacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetalleCotizacionRepository extends \Doctrine\ORM\EntityRepository
{
}
