<?php

namespace Mbp\FinanzasBundle\Entity;

/**
 * DetalleMovimientosBancosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetalleMovimientosBancosRepository extends \Doctrine\ORM\EntityRepository
{
}
