<?php

namespace Mbp\FinanzasBundle\Entity;

/**
 * FacturaDetalleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacturaDetalleRepository extends \Doctrine\ORM\EntityRepository
{
	
}
