<?php

namespace Mbp\FinanzasBundle\Entity;

/**
 * InteresesResarcitoriosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InteresesResarcitoriosRepository extends \Doctrine\ORM\EntityRepository
{
}
