<?php

namespace Mbp\FinanzasBundle\Entity;

/**
 * MovimientosBancosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovimientosBancosRepository extends \Doctrine\ORM\EntityRepository
{
}
