<?php

namespace Mbp\FinanzasBundle\Entity;

/**
 * ParametrosFinanzasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParametrosFinanzasRepository extends \Doctrine\ORM\EntityRepository
{
}
