<?php

namespace Mbp\FinanzasBundle\Entity;

/**
 * PosicionIVARepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PosicionIVARepository extends \Doctrine\ORM\EntityRepository
{
}
