<?php

namespace Mbp\FinanzasBundle\Entity;

/**
 * TipoIvaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoIvaRepository extends \Doctrine\ORM\EntityRepository
{
}
