<?php

namespace Mbp\FinanzasBundle\Entity;

/**
 * TransaccionCobranzaFacturaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransaccionCobranzaFacturaRepository extends \Doctrine\ORM\EntityRepository
{
	public function getTotalAplicadoFactura($idFactura)
	{
		$em = $this->getEntityManager();
		$repo = $em->getRepository('MbpFinanzasBundle:TransaccionCobranzaFactura');
		
		$qb = $repo->createQueryBuilder('tr')
			->select('SUM(tr.aplicado) as aplicado')
			->where('tr.facturaImputada = :idFc')
			->setParameter('idFc', $idFactura)
			->getQuery()
			->getArrayResult();
		
		return $qb[0]['aplicado'];
	}
}
