<?php

namespace Mbp\FinanzasBundle\Entity;

/**
 * TransaccionCobranzaFacturaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransaccionCobranzaFacturaRepository extends \Doctrine\ORM\EntityRepository
{
}
