<?php

namespace Mbp\ArticulosBundle\Entity;

/**
 * ConceptosStockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConceptosStockRepository extends \Doctrine\ORM\EntityRepository
{
}
