<?php

namespace Mbp\ArticulosBundle\Entity;

/**
 * DepositoArticulosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepositoArticulosRepository extends \Doctrine\ORM\EntityRepository
{
}
