<?php

namespace Mbp\ArticulosBundle\Entity;

/**
 * DetalleMovArtRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetalleMovArtRepository extends \Doctrine\ORM\EntityRepository
{
}
