<?php

namespace Mbp\ArticulosBundle\Entity;

/**
 * PosEnfriadoresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnfriadoresRepository extends \Doctrine\ORM\EntityRepository
{
}
