<?php

namespace Mbp\ArticulosBundle\Entity;

/**
 * FamiliaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FamiliaRepository extends \Doctrine\ORM\EntityRepository
{
	public function nuevaFamilia($familia)
	{
		$em = $this->getEntityManager();
		
		$fam = new Familia();
		$fam->setFamilia($familia);
				
		try{
			$em->persist($fam);
			$em->flush();
			return $fam->getId();	
		}catch(\Exception $e){
			return $e->getMessage();
		}		
	}
	
	public function actualizarReg($data)
	{
		$em = $this->getEntityManager();
		$repo = $em->getRepository('MbpArticulosBundle:Familia');
				
		try{
			$fam = $repo->find($data->idFamilia);
		
			$fam->setFamilia($data->familia);
			$em->persist($fam);
			$em->flush();	
			return 1;
		}catch(\Exception $e){
			return $e->getMessage();
		}
	}
	
	public function eliminarReg($data)
	{
		$em = $this->getEntityManager();
		$repo = $em->getRepository('MbpArticulosBundle:Familia');
				
		try{
			$fam = $repo->find($data->idFamilia);
			$fam->setisActive(1);
			$em->persist($fam);
			$em->flush();	
			return 1;
		}catch(\Exception $e){
			return $e->getMessage();
		}
	}
}
