<?php

namespace Mbp\ArticulosBundle\Entity;

/**
 * ListaPreciosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListaPreciosRepository extends \Doctrine\ORM\EntityRepository
{
}
