<?php

namespace Mbp\ArticulosBundle\Entity;

/**
 * MovimientosArticulosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovimientosArticulosRepository extends \Doctrine\ORM\EntityRepository
{
	public function listarPendientesVerificacion()
	{
		$em = $this->getEntityManager();
		$repoMov = $em->getRepository('MbpArticulosBundle:MovimientosArticulos');
		$qb = $repoMov->createQueryBuilder('mov')
			->select('
				mov.fechaMovimiento AS fecha,
				art.codigo,
				det.descripcion,
				det.id AS loteNum,
				oc.id AS idOc,
				det.cantidad AS cant,
				det.estadoCalidad,
				det.certificadoNum,
				det.id AS id
				')
			->join('mov.movDetalleId', 'det')
			->join('mov.proveedorId', 'prov')
			->join('det.articuloId', 'art')
			->join('det.ordenCompraId', 'oc')
			->where('art.requiereControl = 1')
			->andWhere('det.estadoCalidad is NULL')
			->getQuery()
			->getArrayResult();	
		return $qb;	
	}
}
