<?php

namespace Mbp\ArticulosBundle\Entity;

/**
 * MovimientosArticulosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovimientosArticulosRepository extends \Doctrine\ORM\EntityRepository
{
}
