<?php

namespace Mbp\ArticulosBundle\Entity;

/**
 * RemitosClientesDetallesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RemitosClientesDetallesRepository extends \Doctrine\ORM\EntityRepository
{
}
