<?php

namespace Mbp\ArticulosBundle\Entity;

/**
 * RemitosClientesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RemitosClientesRepository extends \Doctrine\ORM\EntityRepository
{
}
