<?php

namespace Mbp\ArticulosBundle\Entity;

/**
 * SubFamiliaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubFamiliaRepository extends \Doctrine\ORM\EntityRepository
{
	public function nuevaSubFamilia($subFamilia)
	{
		$em = $this->getEntityManager();
		
		$fam = new SubFamilia();
		$fam->setSubFamilia($subFamilia);
				
		try{
			$em->persist($fam);
			$em->flush();
			return $fam->getId();	
		}catch(\Exception $e){
			return $e->getMessage();
		}		
	}
	
	public function actualizarReg($data)
	{
		$em = $this->getEntityManager();
		$repo = $em->getRepository('MbpArticulosBundle:SubFamilia');
				
		try{
			$fam = $repo->find($data->idSubFamilia);
		
			$fam->setSubFamilia($data->subFamilia);
			$em->persist($fam);
			$em->flush();	
			return 1;
		}catch(\Exception $e){
			return $e->getMessage();
		}
	}
	
	public function eliminarReg($data)
	{
		$em = $this->getEntityManager();
		$repo = $em->getRepository('MbpArticulosBundle:SubFamilia');
				
		try{
			$fam = $repo->find($data->idSubFamilia);
			$fam->setisActive(1);
			$em->persist($fam);
			$em->flush();	
			return 1;
		}catch(\Exception $e){
			return $e->getMessage();
		}
	}
}
