<?php

namespace Mbp\ProduccionBundle\Entity;

/**
 * MaquinasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaquinasRepository extends \Doctrine\ORM\EntityRepository
{
	public function listarMaquinas()
	{
		$em = $this->getEntityManager();
		$repo = $em->getRepository('MbpProduccionBundle:Maquinas');
		
		try{
			$dql = 'SELECT m, s FROM MbpProduccionBundle:Maquinas m
					LEFT JOIN m.sector s
					';
			$query = $em->createQuery($dql);
			$maq = $query->getArrayResult();
		}catch(\Doctrine\ORM\ORMException $e){
			$this->get('logger')->error($e->getMessage());
		}
		 
		 echo json_encode($maq);
	}
	
	public function buscaxSector($dato)
	{
		try{
			$em = $this->getEntityManager();
			$repoMaquinas = $em->getRepository('MbpProduccionBundle:Maquinas');
			$repoSectores = $em->getRepository('MbpProduccionBundle:Sectores');
			
			$sector = $repoSectores->findBydescripcion($dato);
			$idSector = $sector[0]->getId();
			
			//TRAIGO MAQUINAS DE ACUERDO AL SECTOR DONDE SE ENCUENTRAN
			$dql = 'SELECT m, s FROM MbpProduccionBundle:Maquinas m				
					JOIN m.sector s
					WHERE m.sector = :sector';
			$query = $em->createQuery($dql)
						->setParameter('sector', $idSector);	
			$res = $query->getArrayResult();
			
			echo json_encode($res);	
		}catch(\Doctrine\ORM\ORMException $e){
			$this->get('logger')->error($e->getMessage());
		}
	}
}





