<?php
namespace Mbp\ProduccionBundle\Entity;

/**
 * PedidoClientesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PedidoClientesRepository extends \Doctrine\ORM\EntityRepository
{
	
	public function listarPedidos()
	{
		try{
			$em = $this->getEntityManager();
			$repo = $em->getRepository('MbpProduccionBundle:PedidoClientes');
			$res = $repo->findByInactivo(0);
			$info = array();
			
			for($i=0; $i<count($res); $i++){				
					$info[$i]['codigo'] = $res[$i]->getCodigo()->getCodigo();
					$info[$i]['descripcion'] = $res[$i]->getCodigo()->getDescripcion();
					$info[$i]['cantidad'] = $res[$i]->getCantidad();
					$info[$i]['clienteDesc'] = $res[$i]->getCliente()->getRsocial();
					$info[$i]['fechaProgramacion'] = $res[$i]->getFechaProg();				
			}
			
			echo json_encode($info);
			
		}catch(\Doctrine\ORM\ORMException $e){
			$this->get('logger')->error($e->getMessage());
			echo json_encode(array(
				'success' => false,
				'msg' => $e->getMessage()
			));
		}
	}

	public function pedidosPorArticuloCliente($codigo, $idCliente)
	{
		$em = $this->getEntityManager();
		$repo = $em->getRepository('MbpProduccionBundle:PedidoClientes');

		$qb = $repo->createQueryBuilder('p')
			->select('p.oc, p.id as pedidoNum, art.codigo, det.entregado, det.cantidad, (det.cantidad - det.entregado) AS pendiente')
			->join('p.detalleId', 'det')
			->join('det.codigo', 'art')
			->where('art.codigo = :cod')
			->andWhere('p.cliente = :cliente')
			->andWhere('det.inactivo = 0')
			->setParameter('cliente' , $idCliente)
			->setParameter('cod' , $codigo)
			->getQuery()
			->getArrayResult();

		return $qb;

	}
}






















