<?php

namespace Mbp\ProduccionBundle\Entity;

/**
 * PedidoClientesDetalleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PedidoClientesDetalleRepository extends \Doctrine\ORM\EntityRepository
{
}
