<?php

namespace Mbp\ProduccionBundle\Entity;

/**
 * ProduccionSoldadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduccionSoldadoRepository extends \Doctrine\ORM\EntityRepository
{
}
