<?php

namespace Mbp\ProduccionBundle\Entity;

/**
 * ProgParamsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProgParamsRepository extends \Doctrine\ORM\EntityRepository
{
}
