<?php

namespace Mbp\ProduccionBundle\Entity;

/**
 * SectoresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SectoresRepository extends \Doctrine\ORM\EntityRepository
{
	public function buscaSector($sector)
	{
		$em = $this->getEntityManager();
		$repo = $em->getRepository('MbpProduccionBundle:Sectores');
		
		try{
			$res = $repo->findByDescripcion($sector);
			
			//RESPUESTA
			echo json_encode(array(
				'id' => $res[0]->getId(),
				'costo' => $res[0]->getCostoMin(),
				'tiempo' => $res[0]->getTiempo(),
			));	
		}catch(\Doctrine\ORM\ORMException $e){
			$this->get('logger')->error($e->getMessage());
			echo json_encode(array(
				'success' => false,
				'msg' => $e->getMessage()
			));
		}
		
	}
	
	public function listarSectores()
	{
		$em = $this->getEntityManager();
		$dql = 'SELECT sec FROM MbpProduccionBundle:Sectores sec';
		
		
		try{
			$query = $em->createQuery($dql);
			$res = $query->getArrayResult();
						
			echo json_encode($res);
			
		}catch(\Doctrine\ORM\ORMException $e){
			$this->get('logger')->error($e->getMessage());
		}
	}
	
	public function personalEnSector($sector)
	{
		try{
			$em = $this->getEntityManager();
			
			if($sector){
				$dql = 'SELECT personal.nombre, personal.idP
					FROM MbpPersonalBundle:Personal personal
					JOIN personal.sector sector
					WHERE sector.descripcion = :sector
				';
				
				$query = $em->createQuery($dql)
							->setParameter('sector', $sector);
				$res = $query->getArrayResult();
				
				echo json_encode($res);	
			}else{
				$dql = 'SELECT sector FROM MbpProduccionBundle:Sectores sector';
				
				$query = $em->createQuery($dql);
				$res = $query->getArrayResult();
				
				echo json_encode($res);
			}				
		}catch(\Doctrine\ORM\ORMException $e){
			$this->get('logger')->error($e->getMessage());
			echo json_encode(array(
				'success' => false,
				'msg' => $e->getMessage()
			));
		}	
		
	}
}
