parameters:
    ptoVta: 1
    docTipo: 80    

services:
    mbp.faele:
        class: Mbp\FinanzasBundle\Clases\Faele
        arguments: [%ptoVta%, %docTipo%]
        
    tipo_cambio:
       class: Mbp\FinanzasBundle\Clases\TipoCambio
       arguments: [ @doctrine.orm.entity_manager ]

    AuxiliarFinanzas:
       class: Mbp\FinanzasBundle\Clases\AuxiliarFinanzas
