parameters:
    ptoVta: 1
    docTipo: 80    
    userArba: 33678767439
    passArba: 336787
    urlArba: 'http://dfe.arba.gov.ar/DomicilioElectronico/SeguridadCliente/dfeServicioConsulta.do'

services:
    mbp.faele:
        class: Mbp\FinanzasBundle\Clases\Faele
        arguments: [%ptoVta%, %docTipo%]
        
    tipo_cambio:
       class: Mbp\FinanzasBundle\Clases\TipoCambio
       arguments: [ @doctrine.orm.entity_manager ]

    AuxiliarFinanzas:
       class: Mbp\FinanzasBundle\Clases\AuxiliarFinanzas
    
    ServiceIIBB:
        class: Mbp\FinanzasBundle\Clases\ServiceIIBB
        arguments: [%userArba%, %passArba%, '%kernel.root_dir%', %urlArba%]
        
    InteresesResarcitorios:
        class: Mbp\FinanzasBundle\Clases\InteresesResarcitorios
        arguments: []