mbp_articulos_read:
    path:     /extranet/articuloslist
    defaults: { _controller: MbpArticulosBundle:Articulos:articuloslist }
    options:
      expose: true

mbp_articulos_conCosto:
    path:     /extranet/articuloConCosto
    defaults: { _controller: MbpArticulosBundle:Articulos:articuloConCosto }
    options:
      expose: true

mbp_articulos_create:
    path:     /articuloscreate
    defaults: { _controller: MbpArticulosBundle:Articulos:articuloscreate }
    options:
      expose: true

mbp_articulos_destroy:
    path:     /articulosdestroy
    defaults: { _controller: MbpArticulosBundle:Articulos:articulosdestroy }
    options:
      expose: true

mbp_articulos_validate:
    path:     /extranet/articulosvalidate
    defaults: { _controller: MbpArticulosBundle:Articulos:validart }
    options:
      expose: true

mbp_articulos_cargarImagen:
    path:     /cargarImagen
    defaults: { _controller: MbpArticulosBundle:Articulos:cargarImagen }
    options:
      expose: true

mbp_articulos_servirImagen:
    path:     /extranet/servirImagen/{id}
    defaults: { _controller: MbpArticulosBundle:Articulos:servirImagenArticulo }
    options:
      expose: true

mbp_articulos_DBF_verEstructura:
    path:     /DBF_verEstructura
    defaults: { _controller: MbpArticulosBundle:Articulos:DBF_verEstructura }
    options:
      expose: true

mbp_articulos_actualizar_base:
    path:     /actualizarArticulosBd
    defaults: { _controller: MbpArticulosBundle:Articulos:actualizarArticulosBd }
    options:
      expose: true

#borrar luego de exportar
mbp_formulas_exportarFormulas3:
    path:     /exportarFormulas3
    defaults: { _controller: MbpArticulosBundle:Formulas2:exportarFormulas3 }
    options:
      expose: true

mbp_formulas_InsertNodo2:
    path:     /formulasInsertNodo2
    defaults: { _controller: MbpArticulosBundle:Formulas2:formulasInsertNodo2 }
    options:
      expose: true

mbp_formulas_exportarFormulas2:
    path:     /exportarFormulas2
    defaults: { _controller: MbpArticulosBundle:Formulas2:exportarFormulas2 }
    options:
      expose: true

mbp_formulas_acomodarCostos:
    path:     /acomodarCostos
    defaults: { _controller: MbpArticulosBundle:Formulas2:acomodarCostos }
    options:
      expose: true

mbp_formulas_pendientesDeFormula:
    path:     /pendientesDeFormula
    defaults: { _controller: MbpArticulosBundle:Formulas2:pendientesDeFormula }
    options:
      expose: true

mbp_formulas_read:
    path:     /extranet/formulaslist
    defaults: { _controller: MbpArticulosBundle:Formulas2:formulaslist }
    options:
      expose: true

mbp_formulas_InsertNodo:
    path:     /formulasInsertNodo
    defaults: { _controller: MbpArticulosBundle:Formulas2:formulasInsertNodo }
    options:
      expose: true

mbp_formulas_BorrarNodo:
    path:     /formulasBorrarNodo
    defaults: { _controller: MbpArticulosBundle:Formulas2:formulasBorrarNodo }
    options:
      expose: true

mbp_formulas_updateNodo:
    path:     /formulasUpdateNodo
    defaults: { _controller: MbpArticulosBundle:Formulas2:formulasUpdateNodo }
    options:
      expose: true

mbp_formulas_idNodo:
    path:     /extranet/formulasIdNodo
    defaults: { _controller: MbpArticulosBundle:Formulas2:formulasIdNodo }
    options:
      expose: true

mbp_articulos_remitoClientes:
    resource: "@MbpArticulosBundle/Controller/RemitosController.php"
    type:     annotation
    prefix:   /articulos

mbp_articulos_enfriadores:
    resource: "@MbpArticulosBundle/Controller/EnfriadoresController.php"
    type:     annotation
    prefix:   /extranet

mbp_articulos_stock:
    resource: "@MbpArticulosBundle/Controller/StockController.php"
    type:     annotation
    prefix:   /stock
    
