<?php

namespace Mbp\WebBundle\Entity;

/**
 * AplicacionesRadiadoresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AplicacionesRadiadoresRepository extends \Doctrine\ORM\EntityRepository
{
}
