<?php

namespace Mbp\WebBundle\Entity;

/**
 * ArticulosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticulosRepository extends \Doctrine\ORM\EntityRepository
{

	public function getArticulosSegunCategoria($cat){


		$em = $this->getEntityManager('web');

		$qb = $this->createQueryBuilder('art')
			->select('art.id,
				 art.descripcion,
				 art.rutaHojaDatos as ruta,
				 cat.resenia,
				 cat.descripcion as categoria,
				 cat.imagen,
				 subCat.descripcion as subDesc')
			->join('art.categoriaId', 'cat')
			->leftjoin('art.subCategoriaId', 'subCat')
			->where('cat.id = :idCategoria')
			->setParameter('idCategoria', $cat)			
			->getQuery()
			->getArrayResult();


		return $qb;

	}

	public function listarArtPorSubCat($subCat){
		$em = $this->getEntityManager('web');
		$repo = $em->getRepository('MbpWebBundle:Articulos');

		$qb = $repo->createQueryBuilder('art')
			->select('art.id,
				 art.descripcion',
				 'marca.marca')
			->join('art.subCategoriaId', 'subCat')	
			->join('art.marcaId', 'marca')		
			->where('subCat.id = :idSubCategoria')
			->setParameter('idSubCategoria', $subCat)			
			->getQuery()
			->getArrayResult();


		return $qb;
	}
}
