<?php

namespace Mbp\WebBundle\Entity;

/**
 * CategoriasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriasRepository extends \Doctrine\ORM\EntityRepository
{

	public function listarCategorias()
	{
		$em = $this->getEntityManager();
		$repo = $em->getRepository('MbpWebBundle:Categorias');

		$res = $repo->createQueryBuilder('cat')
			->select('cat.descripcion, cat.id')
			->getQuery()
			->getResult();

		return $res;
	}


}
