<?php

namespace Mbp\WebBundle\Entity;

/**
 * MarcasRadiadoresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarcasRadiadoresRepository extends \Doctrine\ORM\EntityRepository
{
	public function marcasSubCategoria($subCat){
		$em = $this->getEntityManager();
		$repo = $em->getRepository('MbpWebBundle:SubCategoria');

		$res = $repo->createQueryBuilder('subCat')
			->select('marcas.id, marcas.marca')
			->join('subCat.articulos', 'art')
			->join('art.marcaId', 'marcas')
			->where('subCat.id = :subCategoria')
			->setParameter('subCategoria', $subCat)
			->groupBy('marcas.marca')
			->getQuery()
			->getResult();

		return $res;
	}

	public function marcasPorAplicaciones($aplicacionId){
		$em = $this->getEntityManager();
		$repo = $em->getRepository('MbpWebBundle:RadiadoresComerciales');



		$res = $repo->createQueryBuilder('rad')
			->select('marcas.id, marcas.marca')
			->join('rad.aplicacionId', 'aplic')
			->join('rad.marcaId', 'marcas')
			->where('aplic.id = :aplicacion')
			->setParameter('aplicacion', $aplicacionId)
			->groupBy('marcas.marca')
			->getQuery()
			->getResult();


		return $res;
	}
}
