<?php

namespace Mbp\WebBundle\Entity;

/**
 * RadiadoresComercialesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RadiadoresComercialesRepository extends \Doctrine\ORM\EntityRepository
{
	public function listarRadPorAplicacion($aplicacionId){
		$em = $this->getEntityManager('web');
		$repo = $em->getRepository('MbpWebBundle:RadiadoresComerciales');

		$qb = $repo->createQueryBuilder('rad')
			->select('
				 rad.codigoBp as codigo,
				 rad.descripcion,
				 rad.oem,
				 marca.marca,
				 rad.imagenCatalogo as imagen')
			->join('rad.aplicacionId', 'aplicacion')	
			->join('rad.marcaId', 'marca')		
			->where('aplicacion.id = :aplicacion')
			->setParameter('aplicacion', $aplicacionId)			
			->getQuery()
			->getArrayResult();


		return $qb;
	}

	public function listarRadPorTipo($tipo){
		$em = $this->getEntityManager('web');
		$repo = $em->getRepository('MbpWebBundle:TiposRadiadores');

		$qb = $repo->createQueryBuilder('tipos')
			->select('rad.descripcion, rad.oem, marca.marca, rad.codigoBp as codigo, rad.imagenCatalogo as imagen')	
			->join('tipos.aplicacionId', 'aplicacion')
			->join('aplicacion.radiadoresComerciales', 'rad')
			->join('rad.marcaId', 'marca')
			->getQuery()
			->getArrayResult();


		return $qb;
	}

	public function filtrarPorMarca($tipo, $aplicacion, $marca){
		$em = $this->getEntityManager('web');
		$repo = $em->getRepository('MbpWebBundle:TiposRadiadores');
		

		$qb = $repo->createQueryBuilder('tipos')
			->select('rad.descripcion, rad.oem, marca.marca, rad.codigoBp as codigo, rad.imagenCatalogo as imagen')	
			->join('tipos.aplicacionId', 'aplicacion')
			->join('aplicacion.radiadoresComerciales', 'rad')
			->join('rad.marcaId', 'marca')
			->where('tipos.id = :tipo')
			->andWhere('aplicacion.id = :aplicacion')
			->andWhere('marca.id = :marca')
			->setParameter('tipo', $tipo)
			->setParameter('aplicacion', $aplicacion)
			->setParameter('marca', $marca)
			->getQuery()
			->getArrayResult();


		return $qb;
	}
}
