<?php

namespace Mbp\WebBundle\Entity;

/**
 * SubCategoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubCategoriaRepository extends \Doctrine\ORM\EntityRepository
{
}
