<?php

namespace Mbp\ClientesBundle\Entity;

/**
 * Clientes_FamiliasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Clientes_FamiliasRepository extends \Doctrine\ORM\EntityRepository
{
}
