<?php

namespace Mbp\ClientesBundle\Entity;

/**
 * TransportesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransportesRepository extends \Doctrine\ORM\EntityRepository
{
	public function listar(){
		$em = $this->getEntityManager();
		$rep = $em->getRepository('MbpClientesBundle:Transportes');		
		$qb = $rep->createQueryBuilder('t')
			->select('t.id, t.nombre, t.direccion, t.telefono, t.contacto, t.horarios, p.nombre as provincia, d.nombre as departamento')
			->leftJoin('t.departamento', 'd')
			->leftJoin('d.provinciaId', 'p')
			->where('t.inactivo = 0')
			->getQuery()
			->getArrayResult();
			
		return $qb;
	}
}
