<?php

namespace Mbp\ProveedoresBundle\Entity;

/**
 * ImputacionGastosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImputacionGastosRepository extends \Doctrine\ORM\EntityRepository
{
}
