<?php

namespace Mbp\ProveedoresBundle\Entity;

/**
 * OrdenPagoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdenPagoRepository extends \Doctrine\ORM\EntityRepository
{
	public function listarValoresOP($idOP)
	{
		$em = $this->getEntityManager();
		$repo = $em->getRepository('MbpProveedoresBundle:OrdenPago');
		$qb = $repo->createQueryBuilder('op');
		$query = $qb->select('op.id AS idOP, d.banco, d.emision, d.numero, d.importe, d.diferido, fp.descripcion AS formaPago')
				->join('op.pagoDetalleId', 'd')
				->join('d.idFormaPago', 'fp')
				->where('op.id = :idOP')
				->setParameter('idOP', $idOP)
				->getQuery();
		
		$res = $query->getResult();
		
		for ($i=0; $i < count($res); $i++) { 
			$res[$i]['diferido'] = $res[$i]['diferido']->format('d/m/Y'); 
		}
		
		return $res;
	}
}
