<?php

namespace Mbp\ProveedoresBundle\Entity;

/**
 * TransaccionOPFCRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransaccionOPFCRepository extends \Doctrine\ORM\EntityRepository
{
}
