<?php

namespace Mbp\ProveedoresBundle\Entity;

/**
 * TransaccionOPFCRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransaccionOPFCRepository extends \Doctrine\ORM\EntityRepository
{
	public function selectSumImputacionByFc($fc){
		$em = $this->getEntityManager();
		$repo = $em->getRepository('MbpProveedoresBundle:TransaccionOPFC');

		$res = $repo->createQueryBuilder("t")
			->select("SUM(t.aplicado) as total")			
			->where("t.facturaImputada = :fc")
			->setParameter("fc", $fc)
			->getQuery()
			->getOneOrNullResult();

		return $res;
	}
}
