services:
    eliminar_op:
        class: Mbp\ProveedoresBundle\Listener\EliminarOPListener
        tags:
          - { name: doctrine.event_listener, event: preRemove }
    eliminar_fc:
        class: Mbp\ProveedoresBundle\Listener\EliminarFCListener
        tags:
          - { name: doctrine.event_listener, event: preRemove }
    Pagos:
        class: Mbp\ProveedoresBundle\Listener\PagosListener
        tags:
          - { name: doctrine.event_listener, event: postPersist }