services:
    pago_cheque_terceros:
        class: Mbp\ProveedoresBundle\Listener\PagosListener
        arguments: [ @doctrine.orm.entity_manager ]
        tags:
          - { name: kernel.event_listener, event: kernel.request }
    eliminar_op:
        class: Mbp\ProveedoresBundle\Listener\EliminarOPListener
        tags:
          - { name: doctrine.event_listener, event: preRemove }
    eliminar_fc:
        class: Mbp\ProveedoresBundle\Listener\EliminarFCListener
        tags:
          - { name: doctrine.event_listener, event: preRemove }
    movimientoBancario:
        class: Mbp\ProveedoresBundle\Listener\MovimientoBancarioListener
        tags:
          - { name: doctrine.event_listener, event: postPersist }