login:
    path:     /login
    defaults: { _controller: MbpSecurityBundle:Default:login }
    options:
        expose: true

login_check:
    path: /login_check
    defaults:

logout:
    pattern: logout
    options:
        expose: true

sesion:
    path: /sesion
    defaults: { _controller: MbpSecurityBundle:Default:sesion }
    options:
        expose: true
