parameters:
#    mbp_security.example.class: Mbp\SecurityBundle\Example

services:
#    mbp_security.example:
#        class: %mbp_security.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
